apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashingapi
  namespace: movetokube
spec:
  selector:
    matchLabels:
      app: hashing
  replicas: 2
  template:
    metadata:
      labels:
        app: hashing
    spec:
      containers:
        - name: app
          image: hitman99/hashing:alpha
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "32Mi"
              cpu: "50m"