swagger: "2.0"
info:
  title: Hashing Service
  description: Service for hashing strings
  version: ""
host: 0.0.0.0:8080
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /md5/{string}:
    get:
      tags:
      - hashing
      summary: md5 hashing
      operationId: hashing#md5
      parameters:
      - name: string
        in: path
        description: String to hash
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/HashingMd5ResponseBody'
      schemes:
      - http
  /openapi.json:
    get:
      summary: Download ./static/openapi.json
      operationId: hashing#/openapi.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
  /sha1/{string}:
    get:
      tags:
      - hashing
      summary: sha1 hashing
      operationId: hashing#sha1
      parameters:
      - name: string
        in: path
        description: String to hash
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/HashingSha1ResponseBody'
      schemes:
      - http
  /sha256/{string}:
    get:
      tags:
      - hashing
      summary: sha256 hashing
      operationId: hashing#sha256
      parameters:
      - name: string
        in: path
        description: String to hash
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/HashingSha256ResponseBody'
      schemes:
      - http
  /sha384/{string}:
    get:
      tags:
      - hashing
      summary: sha384 hashing
      operationId: hashing#sha384
      parameters:
      - name: string
        in: path
        description: String to hash
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/HashingSha384ResponseBody'
      schemes:
      - http
  /sha512/{string}:
    get:
      tags:
      - hashing
      summary: sha512 hashing
      operationId: hashing#sha512
      parameters:
      - name: string
        in: path
        description: String to hash
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/HashingSha512ResponseBody'
      schemes:
      - http
definitions:
  HashingMd5ResponseBody:
    title: 'Mediatype identifier: hashingresult; view=default'
    type: object
    properties:
      hash:
        type: string
        description: Hash string in hex format
        example: Sunt nihil ipsum ab sapiente.
      type:
        type: string
        description: Hashing algorithm
        example: Nobis quidem sint molestiae corrupti provident placeat.
    description: Md5ResponseBody result type (default view)
    example:
      hash: Molestias accusamus mollitia dolores.
      type: Recusandae nulla eaque.
  HashingSha1ResponseBody:
    title: 'Mediatype identifier: hashingresult; view=default'
    type: object
    properties:
      hash:
        type: string
        description: Hash string in hex format
        example: Laboriosam aut deserunt inventore laboriosam.
      type:
        type: string
        description: Hashing algorithm
        example: Minus blanditiis.
    description: Sha1ResponseBody result type (default view)
    example:
      hash: Omnis eos nihil nulla omnis libero velit.
      type: Commodi dolorem non sed at dolore.
  HashingSha256ResponseBody:
    title: 'Mediatype identifier: hashingresult; view=default'
    type: object
    properties:
      hash:
        type: string
        description: Hash string in hex format
        example: Libero ducimus perferendis distinctio nam.
      type:
        type: string
        description: Hashing algorithm
        example: Tempora est non.
    description: Sha256ResponseBody result type (default view)
    example:
      hash: Quia modi sit expedita dolores.
      type: Sed sed aliquid mollitia.
  HashingSha384ResponseBody:
    title: 'Mediatype identifier: hashingresult; view=default'
    type: object
    properties:
      hash:
        type: string
        description: Hash string in hex format
        example: Repellat veritatis expedita et et eligendi.
      type:
        type: string
        description: Hashing algorithm
        example: Est ab.
    description: Sha384ResponseBody result type (default view)
    example:
      hash: Eligendi qui temporibus eum.
      type: Qui aut quasi.
  HashingSha512ResponseBody:
    title: 'Mediatype identifier: hashingresult; view=default'
    type: object
    properties:
      hash:
        type: string
        description: Hash string in hex format
        example: Adipisci quos sunt qui.
      type:
        type: string
        description: Hashing algorithm
        example: Sit debitis consequatur quaerat perspiciatis.
    description: Sha512ResponseBody result type (default view)
    example:
      hash: Quas minima porro earum blanditiis aspernatur.
      type: Cum sit molestiae ipsum asperiores ea facilis.
